name: check_lint

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: check-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit black isort clang-format
      - name: Run lint
        run: |
          pre-commit run --all-files
